# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyOcnPGVZHpETPSrjbq1Sja4QH9Cv5TS
"""

!pip install pdfplumber
import pdfplumber
import pandas as pd

def extract_text_from_pdf(pdf_path):
    text_data = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text_data.append(page.extract_text())
    return "\n".join(text_data) if text_data else "No text extracted"

def search_keywords(text, keywords):
    results = []
    lines = text.split("\n")
    seen_snippets = set()

    for keyword in keywords:
        for i, line in enumerate(lines):
            if keyword.lower() in line.lower():
                content_snippet = "\n".join(lines[max(0, i-2): min(len(lines), i+3)])
                if content_snippet not in seen_snippets:
                    results.append({"Keyword": keyword, "Extracted Content": content_snippet})
                    seen_snippets.add(content_snippet)

    return results

def save_to_excel(data, excel_filename, source_book_name):
    df = pd.DataFrame(data)
    df['Source Book'] = source_book_name
    df.to_excel(excel_filename, index=False)
    print(f"✅ Data saved to {excel_filename}")

def process_pdf(pdf_path, keywords, output_excel, source_book_name):
    extracted_text = extract_text_from_pdf(pdf_path)
    extracted_data = search_keywords(extracted_text, keywords)

    if extracted_data:
        save_to_excel(extracted_data, output_excel, source_book_name)
    else:
        print("❌ No matches found for the given keywords!")

pdf_file = "/content/Engineering+Working+Drawing+Basics.pdf"
keywords = ["Codes and Standards","Material or Parts List"]
output_excel = "/content/document_extraction.xlsx"
source_book_name = "Engineering+Working+Drawing+Basics"

process_pdf(pdf_file, keywords, output_excel, source_book_name)

from google.colab import files
files.download("/content/document_extraction.xlsx")

!pip install PyPDF2
import re
from PyPDF2 import PdfReader
import pandas as pd

pdf_path = '/content/Autodesk Inventor Practice Part Drawings.pdf'
reader = PdfReader(pdf_path)

pdf_text = [page.extract_text() for page in reader.pages]
combined_text = " ".join(pdf_text)

pattern = re.compile(r"([A-Za-z0-9\s,-]+\.ipt)(.*?)(?=(?:[A-Za-z0-9\s,-]+\.ipt|$))", re.DOTALL)
matches = pattern.findall(combined_text)

parsed_data = [{"Name": match[0].strip(), "Content": match[1].strip()} for match in matches]
df = pd.DataFrame(parsed_data)

output_path = 'documentation_intelligence.xlsx'
df.to_excel(output_path, index=False)

print(f"Extraction completed. Data saved to {output_path}.")

from google.colab import files
files.download("/content/documentation_intelligence.xlsx")